SELECT "ID", "SERVICE_ID", "PRODUCT_ID", "SPS_PRODUCT_NAME", "SERVICE_CODE",
       "DURATION", "DUR", "MONTH_EXPIRE", "PRICE", "MB",
       "RESET_PERIOD_VOLUME", "PC_GROUP_ID", "PC_GROUP_SERVICE_TYPE",
       "REPORTING_GROUP", "SUBSCRIPTIONTYPE", "SERVICE_GROUP", "SUB_GROUP",
       "FIX_PDPCP", "SERVICE_SAPC", "OCSE", "ACCEPT_PREFIX", "MTR_COMMENT",
       "CTL_KMX","PROV_SYSTEM"
FROM (SELECT A.ID, A.SERVICE_ID, A.SERVICE_CODE, P.PRODUCT_ID,
             P.PRODUCTNAME AS SPS_PRODUCT_NAME, P.DURATION, P.DUR,
             P.MONTH_EXPIRE, P.PRICE,
             ROUND (PCG2.HIGH_VOL / (1024 * 1024)) MB,
             PCG3.RESET_PERIOD_VOLUME, PC_GROUP_ID, REPORTING_GROUP,
             SUBSCRIPTIONTYPE, SERVICE_GROUP, SUB_GROUP, FIX_PDPCP,
             SERVICE_SAPC, OCSE, ACCEPT_PREFIX, MTR_COMMENT, CTL_KMX,
             PC_GROUP_SERVICE_TYPE, spi.PROV_SYSTEM
      FROM (SELECT ID, SERVICE_ID, SERVICE_CODE
            FROM RND_SUPPORT.SPI_PRODUCT_SERVICE@BI_VNP) A,
           (select SERVICE_ID, SERVICE_CODE,PROVISIONING_SYSTEM PROV_SYSTEM from SUBADMIN.SPI_SERVICE_CODES@BI_VNP)spi,
           (SELECT PRODUCT_ID, PRODUCTNAME, DURATION,
                   REGEXP_REPLACE (NVL (DURATION, '0'), '[^0-9.]', '') DUR,
                   RE_SUBCRIPTION, SERVICE_CODE,
                   TO_NUMBER (NVL (PRICE, '0')) PRICE, VOLUME, MONTH_EXPIRE,
                   CTL_KMX
            FROM RND_SUPPORT.TABLE_CONFIG_PRODUCT@BI_VNP) P,
           (SELECT SERVICE_CODE, SERVICE_GROUP, SUB_GROUP, SERVICE_SAPC
            FROM RND_SUPPORT.SPI_SUBGROUPS@BI_VNP) G,
           (SELECT SER_ID, MAX (PARAM_VALUE) PC_GROUP_ID
            FROM RND_SUPPORT.SPI_PRODUCT_SERVICE_PARAM@BI_VNP
            WHERE PARAM_NAME = 'GROUP_ID'
            GROUP BY SER_ID) PCG,
           (SELECT SER_ID,
                   MAX (NVL (REGEXP_SUBSTR (PARAM_VALUE, '([0-9]+)', 1, 1, NULL, 1), 0)) HIGH_VOL
            FROM RND_SUPPORT.SPI_PRODUCT_SERVICE_PARAM@BI_VNP
            WHERE     PARAM_NAME IN ('HIGH_VOLUME', 'OCS_DA1_VOL')
                  AND PARAM_VALUE NOT LIKE '%|%'
            GROUP BY SER_ID) PCG2,
           (SELECT SER_ID, MAX (PARAM_VALUE) RESET_PERIOD_VOLUME
            FROM RND_SUPPORT.SPI_PRODUCT_SERVICE_PARAM@BI_VNP
            WHERE PARAM_NAME = 'RESET_PERIOD_VOLUME'
            GROUP BY SER_ID) PCG3,
           (SELECT SER_ID,
                   MAX (CASE PARAM_NAME WHEN 'REPORTING_GROUP' THEN PARAM_VALUE ELSE NULL END) REPORTING_GROUP,
                   MAX (CASE PARAM_NAME WHEN 'SUBSCRIPTIONTYPE' THEN PARAM_VALUE ELSE NULL END) SUBSCRIPTIONTYPE,
                   MAX (CASE PARAM_NAME WHEN 'FIX_PDPCP' THEN PARAM_VALUE ELSE NULL END) FIX_PDPCP
            FROM RND_SUPPORT.SPI_PRODUCT_SERVICE_PARAM@BI_VNP
            WHERE PARAM_NAME IN ('REPORTING_GROUP', 'SUBSCRIPTIONTYPE',
                                 'FIX_PDPCP')
            GROUP BY SER_ID) PCG4,
           (SELECT SER_ID, MAX (PARAM_VALUE) OCSE
            FROM RND_SUPPORT.SPI_PRODUCT_SERVICE_PARAM@BI_VNP
            WHERE PARAM_NAME = 'OCSE'
            GROUP BY SER_ID) PCG5,
           (SELECT VALUE_NEW G,
                   LISTAGG (ACCEPTION, ',') WITHIN GROUP (ORDER BY ACCEPTION) ACCEPT_PREFIX
            FROM RND_SUPPORT.TABLE_LOOKUPS@BI_VNP
            WHERE TYPE_ID = '45' AND ACCEPTION = '8487'
            GROUP BY VALUE_NEW) PCG6,
           (SELECT DISTINCT SERVICE_CODE,
                            MAX (MTR_COMMENT) KEEP (DENSE_RANK LAST ORDER BY DATETIME) OVER (PARTITION BY SERVICE_CODE) MTR_COMMENT
            FROM RND_SUPPORT.PRODUCT_COMPONENT_RATIO@BI_VNP) PCG7,
           (SELECT DISTINCT GROUP_ID,
                            MAX (SERVICE_TYPE) KEEP (DENSE_RANK LAST ORDER BY ROWID) OVER (PARTITION BY GROUP_ID) PC_GROUP_SERVICE_TYPE
            FROM RND_SUPPORT.SPI_SERVICE_GROUP_CONFIG@BI_VNP) PCG8
      WHERE     A.SERVICE_CODE = P.SERVICE_CODE
            AND A.SERVICE_CODE = G.SERVICE_CODE
            and a.SERVICE_CODE=spi.SERVICE_CODE(+)
            AND A.ID = PCG.SER_ID(+)
            AND A.ID = PCG2.SER_ID(+)
            AND A.ID = PCG3.SER_ID(+)
            AND A.ID = PCG4.SER_ID(+)
            AND A.ID = PCG5.SER_ID(+)
            AND PCG.PC_GROUP_ID = PCG8.GROUP_ID(+)
            AND G.SERVICE_GROUP = PCG6.G(+)
            AND A.SERVICE_CODE = PCG7.SERVICE_CODE(+))
            
            
    
    
    hehe
            